# Generated by Django 4.0.2 on 2023-07-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knockout', '0004_remove_roundof16_match_number_roundof16_date_and_more'),
        ('tournament', '0008_alter_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytournament',
            name='paired_teams',
            field=models.ManyToManyField(blank=True, to='knockout.QualifyTeam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
