# Generated by Django 4.0.2 on 2023-07-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_alter_match_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupclub',
            options={'ordering': ['group', '-points']},
        ),
        migrations.AddField(
            model_name='mytournament',
            name='champion',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mytournament',
            name='current_stage',
            field=models.CharField(choices=[('Group', 'Group Stage'), ('Round32', 'Round of 32'), ('Round16', 'Round of 16'), ('QuarterFinal', 'Quarter Final'), ('SemiFinal', 'Semi Final'), ('Final', 'Final'), ('End', 'END')], default='Group', max_length=20),
        ),
        migrations.AlterField(
            model_name='mytournament',
            name='teams_selection',
            field=models.CharField(choices=[('4', '4 Teams'), ('8', '8 Teams'), ('16', '16 Teams'), ('32', '32 Teams'), ('64', '64 Teams')], max_length=2),
        ),
    ]
