# Generated by Django 4.0.2 on 2023-07-30 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftms', '0002_alter_club_club_image'),
        ('tournament', '0011_alter_groupclub_options_mytournament_champion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytournament',
            name='champion',
            field=models.ForeignKey(blank=True, default='-', null=True, on_delete=django.db.models.deletion.CASCADE, to='ftms.club'),
        ),
    ]
