# Generated by Django 4.0.2 on 2023-07-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_alter_mytournament_champion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytournament',
            name='current_stage',
            field=models.CharField(choices=[('Group', 'Group Stage'), ('Round32', 'Round of 32'), ('Round16', 'Round of 16'), ('QuarterFinal', 'Quarter Finals'), ('SemiFinal', 'Semi Finals'), ('Final', 'Final'), ('End', 'Tournament End')], default='Group', max_length=20),
        ),
    ]
