# Generated by Django 4.2.4 on 2023-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_alter_mytournament_current_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupclub',
            options={'ordering': ['group', '-points', '-gd']},
        ),
        migrations.AddField(
            model_name='groupclub',
            name='group_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
