# Generated by Django 4.2.4 on 2023-08-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_remove_groupclub_group_number_alter_group_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
