# Generated by Django 4.2.4 on 2023-08-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_match_match_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-group', 'tournament']},
        ),
        migrations.AlterField(
            model_name='match',
            name='match_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
