# Generated by Django 4.2.4 on 2023-08-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_alter_match_options_alter_match_match_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclub',
            name='group_table_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
