# Generated by Django 4.2.4 on 2023-08-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0022_alter_groupclub_group_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='next_group_table_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
