# Generated by Django 4.2.4 on 2023-08-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_group_next_group_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='next_group_table_number',
        ),
    ]
