# Generated by Django 4.2.4 on 2023-08-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0024_remove_group_next_group_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclub',
            name='group_table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
