# Generated by Django 4.2.4 on 2023-08-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0026_alter_groupclub_group_table_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupclub",
            options={"ordering": ["tournament", "group", "-points", "-gd"]},
        ),
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["tournament", "group", "match_number"]},
        ),
        migrations.AlterModelOptions(
            name="mytournament",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="groupclub",
            name="group_table_number",
        ),
    ]
