# Generated by Django 4.2.4 on 2023-08-20 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0027_alter_groupclub_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytournament',
            name='match_per_day',
            field=models.CharField(choices=[(1, '1 Match'), (2, '2 Matches')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='mytournament',
            name='time_match_1',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AddField(
            model_name='mytournament',
            name='time_match_2',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AlterField(
            model_name='mytournament',
            name='teams_selection',
            field=models.CharField(choices=[('4', '4 Teams'), ('8', '8 Teams'), ('16', '16 Teams'), ('32', '32 Teams'), ('64', '64 Teams')], default='4', max_length=2),
        ),
        migrations.AlterField(
            model_name='mytournament',
            name='tournament_type',
            field=models.CharField(choices=[('Groups', 'Groups & Knockout'), ('K/O', 'Knockout')], default='Groups', max_length=8),
        ),
    ]
