# Generated by Django 4.2.4 on 2023-08-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0028_mytournament_match_per_day_mytournament_time_match_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytournament',
            old_name='time_match_1',
            new_name='match_time_1',
        ),
        migrations.RenameField(
            model_name='mytournament',
            old_name='time_match_2',
            new_name='match_time_2',
        ),
        migrations.AlterField(
            model_name='mytournament',
            name='match_per_day',
            field=models.CharField(choices=[('1', '1 Match'), ('2', '2 Matches')], default='1', max_length=1),
        ),
    ]
