# Generated by Django 4.2.4 on 2023-08-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0029_rename_time_match_1_mytournament_match_time_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytournament',
            name='match_per_day',
            field=models.CharField(choices=[('1', '1 Match'), ('2', '2 Matches')], max_length=1),
        ),
        migrations.AlterField(
            model_name='mytournament',
            name='match_time_1',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='mytournament',
            name='match_time_2',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
