# Generated by Django 4.2.4 on 2023-08-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0030_alter_mytournament_match_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytournament',
            name='match_time_1',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
