# Generated by Django 4.2.4 on 2023-08-20 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0031_alter_mytournament_match_time_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytournament',
            name='match_per_day',
            field=models.CharField(choices=[('1', '1 Match'), ('2', '2 Matches')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='mytournament',
            name='match_time_1',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AlterField(
            model_name='mytournament',
            name='match_time_2',
            field=models.TimeField(default=datetime.time),
        ),
    ]
