# Generated by Django 4.2.4 on 2023-08-21 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0032_alter_mytournament_match_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytournament',
            name='match_time_2',
            field=models.TimeField(blank=True, default=datetime.time, null=True),
        ),
    ]
