# Generated by Django 4.2.4 on 2023-08-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0034_alter_clubhistory_id_alter_group_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClubHistory",
        ),
    ]
