# Generated by Django 4.0.2 on 2023-07-24 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_match_tournament'),
        ('knockout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.groupclub')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.mytournament')),
            ],
        ),
    ]
