# Generated by Django 4.0.2 on 2023-07-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knockout', '0002_qualifyteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifyteam',
            name='group_position',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
