# Generated by Django 4.0.2 on 2023-07-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knockout', '0003_qualifyteam_group_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundof16',
            name='match_number',
        ),
        migrations.AddField(
            model_name='roundof16',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2023-07-24T09:45:28.886658Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundof16',
            name='is_match_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roundof16',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_of_16_team1', to='knockout.qualifyteam'),
        ),
        migrations.AlterField(
            model_name='roundof16',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_of_16_team2', to='knockout.qualifyteam'),
        ),
    ]
