# Generated by Django 4.0.2 on 2023-07-24 20:40

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('knockout', '0004_remove_roundof16_match_number_roundof16_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundof16',
            name='date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
