# Generated by Django 4.0.2 on 2023-07-24 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('knockout', '0005_alter_roundof16_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final',
            name='match_number',
        ),
        migrations.RemoveField(
            model_name='quarterfinal',
            name='match_number',
        ),
        migrations.RemoveField(
            model_name='semifinal',
            name='match_number',
        ),
        migrations.RemoveField(
            model_name='thirdplace',
            name='match_number',
        ),
        migrations.AddField(
            model_name='final',
            name='date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='final',
            name='is_match_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarterfinal',
            name='date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='quarterfinal',
            name='is_match_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semifinal',
            name='date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='semifinal',
            name='is_match_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thirdplace',
            name='date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='thirdplace',
            name='is_match_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thirdplace',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_place_team1', to='knockout.semifinal'),
        ),
        migrations.AddField(
            model_name='thirdplace',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_place_team2', to='knockout.semifinal'),
        ),
        migrations.AlterField(
            model_name='final',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_team1', to='knockout.quarterfinal'),
        ),
        migrations.AlterField(
            model_name='final',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_team2', to='knockout.quarterfinal'),
        ),
    ]
