# Generated by Django 4.0.2 on 2023-07-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knockout', '0006_remove_final_match_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundof16',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
