# Generated by Django 4.0.2 on 2023-07-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knockout', '0007_roundof16_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundof16',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_of_16_winner', to='knockout.qualifyteam'),
        ),
    ]
