# Generated by Django 4.0.2 on 2023-07-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knockout', '0008_roundof16_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundof16',
            name='winner',
        ),
        migrations.AddField(
            model_name='qualifyteam',
            name='final_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualifyteam',
            name='quarter_final_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualifyteam',
            name='round_of_16_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualifyteam',
            name='round_of_32_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualifyteam',
            name='semi_final_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarterfinal',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
