# Generated by Django 4.0.2 on 2023-07-24 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knockout', '0009_remove_roundof16_winner_qualifyteam_final_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_team1', to='knockout.qualifyteam'),
        ),
        migrations.AlterField(
            model_name='final',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_team2', to='knockout.qualifyteam'),
        ),
        migrations.AlterField(
            model_name='quarterfinal',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarter_final_team1', to='knockout.qualifyteam'),
        ),
        migrations.AlterField(
            model_name='quarterfinal',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarter_final_team2', to='knockout.qualifyteam'),
        ),
        migrations.AlterField(
            model_name='semifinal',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semi_final_team1', to='knockout.qualifyteam'),
        ),
        migrations.AlterField(
            model_name='semifinal',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semi_final_team2', to='knockout.qualifyteam'),
        ),
        migrations.AlterField(
            model_name='thirdplace',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_place_team1', to='knockout.qualifyteam'),
        ),
        migrations.AlterField(
            model_name='thirdplace',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_place_team2', to='knockout.qualifyteam'),
        ),
    ]
