# Generated by Django 4.0.2 on 2023-07-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knockout', '0010_alter_final_team1_alter_final_team2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifyteam',
            name='third_place_winner',
            field=models.BooleanField(default=False),
        ),
    ]
