# Generated by Django 4.0.2 on 2023-07-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knockout', '0011_qualifyteam_third_place_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifyteam',
            name='sf_loser',
            field=models.BooleanField(default=False),
        ),
    ]
