# Generated by Django 4.0.2 on 2023-07-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knockout', '0013_alter_qualifyteam_group_roundof32'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualifyteam',
            old_name='final_winner',
            new_name='champion',
        ),
        migrations.RenameField(
            model_name='qualifyteam',
            old_name='quarter_final_winner',
            new_name='qfw',
        ),
        migrations.RenameField(
            model_name='qualifyteam',
            old_name='round_of_16_winner',
            new_name='r16w',
        ),
        migrations.RenameField(
            model_name='qualifyteam',
            old_name='round_of_32_winner',
            new_name='r32w',
        ),
        migrations.RenameField(
            model_name='qualifyteam',
            old_name='semi_final_winner',
            new_name='sfl',
        ),
        migrations.RenameField(
            model_name='qualifyteam',
            old_name='sf_loser',
            new_name='sfw',
        ),
        migrations.RenameField(
            model_name='qualifyteam',
            old_name='third_place_winner',
            new_name='tpw',
        ),
    ]
