# Generated by Django 4.0.2 on 2023-07-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_image',
            field=models.ImageField(blank=True, null=True, upload_to='club_images'),
        ),
    ]
