# Generated by Django 4.2.4 on 2023-08-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ftms", "0002_alter_club_club_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={"ordering": ["-created_at"]},
        ),
    ]
